version: '3'
services:
  mysqldb:
    image: mysql:5.7
    restart: always
    container_name: mysqldb-server
    environment: 
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3308:3306
    volumes:
      - ./mysqldb-data:/var/lib/mysql
    networks:
      - base-server-network
  mongodb:
    image: 'bitnami/mongodb:latest'
    restart: always
    container_name: mongodb-server
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/bitnami
    networks:
      - base-server-network
  redis:
    image: 'bitnami/redis:latest'
    restart: always
    container_name: redisdb-server
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - ./redisdb-data:/bitnami
    networks:
      - base-server-network

networks:
  base-server-network: